# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "소개"
  url = "#about"
  weight = 10
  
[[main]]
  name = "서비스"
  url = "#services"
  weight = 20

[[main]]
  name = "블로그"
  url = "#posts"
  weight = 30

[[main]]
  name = "문의"
  url = "#contact"
  weight = 40
  
[[menu.main]]
name = "Projects"
identifier = 'projects'
weight = 50

[[menu.main]]
name = 'printSheetApp'
parent = 'projects'
url = '#projects'
weight = 50


# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/files/cv.pdf` and uncomment the lines below.
# [[main]]
#    name = "CV"
#    url = "files/cv.pdf"
#    weight = 70
